#import Transaction, FindTransactionData, CreateTransactionData, UpdateTransactionData, TransactionResult from "transaction.gql"

#import User, FindUserData, UserResult, CreateUserData from "user.gql"

type Query {
  transactions(data: FindTransactionData): TransactionResult
  users(data: FindUserData): UserResult
}

type Mutation {
  newTransaction(data: CreateTransactionData): Transaction
  updateTransaction(id: String, data: UpdateTransactionData): Transaction
  deleteTransaction(id: String): Transaction
  newUser(data: CreateUserData): User
}
