#import Transaction, FindTransactionData, CreateTransactionData, UpdateTransactionData from "transaction.gql"

type Query {
  transactions(data: FindTransactionData): [Transaction]!
}

type Mutation {
  newTransaction(data: CreateTransactionData): Transaction
  updateTransaction(id: String, data: UpdateTransactionData): Transaction
  deleteTransaction(id: String): Transaction
}
