#import PaginationResult, Pagination from "pagination.gql"

type Transaction {
  id: ID!
  amount: Float!
  type: TransactionType!
  created_at: String!
  updated_at: String
}

enum TransactionType {
  IN
  OUT
}

input FindTransactionData {
  offset: Int
  limit: Int
  initialDate: String
  finalDate: String
}

input CreateTransactionData {
  amount: Float!
  type: TransactionType!
}

input UpdateTransactionData {
  amount: Float
  type: TransactionType
}

type TransactionResult implements PaginationResult {
  count: Int!
  previous: Pagination
  next: Pagination
  items: [Transaction]!
}
