-- Active: 1647898579740@@127.0.0.1@3306
DROP DATABASE IF EXISTS finances;
CREATE DATABASE finances
    DEFAULT CHARACTER SET = 'utf8mb4';

USE finances;

CREATE TABLE accounts (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` TEXT(100) NOT NULL,
  `cpf` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `amount` DECIMAL(14, 2) UNSIGNED DEFAULT 0.00,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP
) engine = InnoDB;

CREATE TABLE transactions (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `account_id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `type` TEXT NOT NULL,
  `value` DECIMAL(14, 2),
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP
) engine = InnoDB;

ALTER TABLE `transactions` ADD FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`);
