-- Active: 1647898579740@@127.0.0.1@3306
CREATE DATABASE finances
    DEFAULT CHARACTER SET = 'utf8mb4';

USE finances;

CREATE TABLE accounts (
  _id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  cpf TEXT NOT NULL,
  password TEXT NOT NULL,
  amount DECIMAL(14, 2) UNSIGNED DEFAULT 0.00,
  createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP
) engine = InnoDB;