version: "3.2"

services:
  postgres:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
