FROM node:16-alpine3.15
WORKDIR /usr
COPY package.json ./
COPY prisma ./prisma/
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install
RUN npx prisma generate
EXPOSE 4005
CMD ["npm","run","dev"]