name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: kinvochallengetest
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run type-check  
      - name: Integration testing
        run: |
          npm run test
        env:
          DATABASE_URL: postgresql://root:admin@localhost:5432/kinvochallengetest?schema=public
          STUDENT_SECRET: 607dcd8c0bb5be4567df79417088bab6
      - name: Deploy application
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kinvochallenge"
          heroku_email: "gustavofvv@gmail.com"
